### ISSUE TITLE
Update to support Joplin Server v2

### ISSUE THREAD

**Issue by crosbyh** [jspiers/docker-joplin-cli#2]
Hello, thank you for publishing this! I'm wondering if it would it be possible to update this container to the latest version of the Joplin cli app? Or allow the user to specify which version to pull via a tag? Joplin versions 2.x support the new syncing server and I'd love to use this container with it.

**Comment by jspiers** [comment]
Hi! Sorry I only got around to this now. I've pushed some changes and now it should be running Joplin 2.4.1. I've also pushed the built docker image to Docker Hub as [jspiers/headless-joplin:2.4.1-node-14.15.5](https://hub.docker.com/layers/jspiers/headless-joplin/2.4.1-node-14.15.5/images/sha256-57e04e0ccc029d7badeec2cae6097f96ac292d675b97473eef983e9721495d6f?context=explore)
I'll close this issue, but feel free to open another if you run into any trouble.
